openapi: 3.0.0
info:
  title: BlogPost API
  description: API to manage blog posts.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Local development server
paths:
  /health:
    get:
      summary: Check API status
      description: Returns the API status to verify if it is working correctly.
      responses:
        '200':
          description: The API is working correctly.
          content:
            application/json:
              schema:
                type: object
                properties:
                  operation:
                    type: string
                    example: 'success'
                  message:
                    type: string
                    example: 'Request successful'
                  timestamp:
                    type: string
                    format: date-time
                    example: '2025-04-06T20:39:49.978Z'
                  data:
                    type: object
                    properties:
                      status:
                        type: string
                        example: 'ok'
